eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8092
spring:
  application:
    name: servicio-reservas
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: demoexp
    url: jdbc:oracle:thin:@192.168.1.20:1521:XE
    username: demoexp
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
